//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Panel.
        /// </summary>
        public static string BackToMainUI {
            get {
                return ResourceManager.GetString("BackToMainUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baidu.
        /// </summary>
        public static string Baidu {
            get {
                return ResourceManager.GetString("Baidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baidu Music.
        /// </summary>
        public static string BaiduMusic {
            get {
                return ResourceManager.GetString("BaiduMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear offline data.
        /// </summary>
        public static string CleanOffline {
            get {
                return ResourceManager.GetString("CleanOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Douban Account.
        /// </summary>
        public static string DoubanAct {
            get {
                return ResourceManager.GetString("DoubanAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Douban Fm.
        /// </summary>
        public static string DoubanFm {
            get {
                return ResourceManager.GetString("DoubanFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download this Song.
        /// </summary>
        public static string DownloadSong {
            get {
                return ResourceManager.GetString("DownloadSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never want to hear this.
        /// </summary>
        public static string HateSong {
            get {
                return ResourceManager.GetString("HateSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like this song.
        /// </summary>
        public static string LikeSong {
            get {
                return ResourceManager.GetString("LikeSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to taskbar tray icon.
        /// </summary>
        public static string Minimize2NotifyIcon {
            get {
                return ResourceManager.GetString("Minimize2NotifyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSN.
        /// </summary>
        public static string Msn {
            get {
                return ResourceManager.GetString("Msn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music FM.
        /// </summary>
        public static string MusicFm {
            get {
                return ResourceManager.GetString("MusicFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Central Room.
        /// </summary>
        public static string MyCentralRoom {
            get {
                return ResourceManager.GetString("MyCentralRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Song.
        /// </summary>
        public static string NextSong {
            get {
                return ResourceManager.GetString("NextSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open desktop lyric.
        /// </summary>
        public static string OpenDeskLrc {
            get {
                return ResourceManager.GetString("OpenDeskLrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open download folder.
        /// </summary>
        public static string OpenDownloadFolder {
            get {
                return ResourceManager.GetString("OpenDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Main Window.
        /// </summary>
        public static string OpenMainWd {
            get {
                return ResourceManager.GetString("OpenMainWd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mini Window.
        /// </summary>
        public static string OpenMiniWd {
            get {
                return ResourceManager.GetString("OpenMiniWd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Application.
        /// </summary>
        public static string QuitApp {
            get {
                return ResourceManager.GetString("QuitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set offline listening.
        /// </summary>
        public static string SetOffline {
            get {
                return ResourceManager.GetString("SetOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down desktop lyric.
        /// </summary>
        public static string ShutDeskLrc {
            get {
                return ResourceManager.GetString("ShutDeskLrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sina Weibo.
        /// </summary>
        public static string SinaWeibo {
            get {
                return ResourceManager.GetString("SinaWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tencent QQ.
        /// </summary>
        public static string TencentQq {
            get {
                return ResourceManager.GetString("TencentQq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Most.
        /// </summary>
        public static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name and Passwrod cannot be empty.
        /// </summary>
        public static string UnamePwdCantEmpty {
            get {
                return ResourceManager.GetString("UnamePwdCantEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password may be wrong.
        /// </summary>
        public static string UnamePwdMayWrong {
            get {
                return ResourceManager.GetString("UnamePwdMayWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Detail.
        /// </summary>
        public static string WeatherDetail {
            get {
                return ResourceManager.GetString("WeatherDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weibo.
        /// </summary>
        public static string Weibo {
            get {
                return ResourceManager.GetString("Weibo", resourceCulture);
            }
        }
    }
}
